#16 actor selection
salceson/miss pull request #21
Opened 2016-12-28 23:20 UTC by mjanczykowski

2016-12-29 09:31 UTC, salceson requested changes

2016-12-29 09:31 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +  private def resolveActor(actorPath: ActorPath): ActorSelection = this.context.actorSelection(actorPath)
I don't like this method name.

2016-12-29 09:31 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +  private def resolveActor(actorPath: ActorPath): ActorSelection = this.context.actorSelection(actorPath)
What is more - is `this` needed here?

2017-01-10 18:38 UTC, salceson commented
Is this necessary?

2017-01-10 19:09 UTC, mjanczykowski commented
I hope not. I'll keep this branch locally and close this PR.

2017-01-10 19:09 UTC, closed without merging