Kryo
salceson/miss pull request #30
Opened 2017-03-06 22:05 UTC by mjanczykowski

2017-03-07 08:46 UTC, salceson requested changes

2017-03-07 08:46 UTC, salceson commented on supervisor/src/main/scala/miss/supervisor/SupervisorApp.scala
> +  val config = ConfigFactory.load("supervisor")
Is worker loading correct config as well?

2017-03-07 08:46 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +                             y: Int) extends SerializableMessage
Put `extends SerializableMessage` in new line.

2017-03-07 08:46 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +                                    availableSpacePerLane: List[Int]) extends SerializableMessage
Put `extends SerializableMessage` in new line.

2017-03-07 08:46 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +                                 outgoingTraffic: List[VehicleAndCoordinates]) extends SerializableMessage
Put `extends SerializableMessage` in new line.

2017-03-19 12:38 UTC, mjanczykowski commented on supervisor/src/main/scala/miss/supervisor/SupervisorApp.scala
> +  val config = ConfigFactory.load("supervisor")
yes, I have changed imports in config files

2017-03-19 12:40 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +                             y: Int) extends SerializableMessage
as you wish, but it doesn't look good

2017-03-19 12:44 UTC, salceson approved these changes
Ok, after CI buils can be merged.

2017-03-22 12:20 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +                             y: Int) extends SerializableMessage
Why?

For me the `extends ...` gets lost if it is in such list of parameters (if they are not in one line), because I put my attention to arguments and not to the superclass.

2017-03-26 13:24 UTC, merged