improved initialization for large towns
salceson/miss pull request #33
Opened 2017-05-02 07:36 UTC by mjanczykowski

All actors resolve their neighbors' actorRefs from paths before starting simulation. Fixes #32 
Using resolveOne to check if actors are alive. And got rid of workers unregistration - now they watch for disassociation events.

2017-05-02 17:14 UTC, salceson requested changes
Can you summarize in "high level" what changes did you do here?

Also found out some things that I think needs changing. Please look at my comments :)

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/supervisor/Supervisor.scala
> +    case Event(ev@DisassociatedEvent(_, _, _), SupervisorData(workers, actors, _)) =>
```case Event(ev: DisassociatedEvent, SupervisorDate(workers, actors, _))```

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +          log.info(s"Cannot resolve actor: $actorPath due to: ${e.getMessage}. Retrying.")
Maybe log with retry time? I mean `retrying for 2nd time` or something similar.

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +    def resolveActorWithRetries(actorPath: ActorPath, retries: Int)(implicit ec: ExecutionContext): Future[ActorRef] = {
Why are you not using here `retry[T]`?

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +    def resolveActorWithRetries(actorPath: ActorPath, retries: Int)(implicit ec: ExecutionContext): Future[ActorRef] = {
Also `actorPath` parameter is not needed IMO. It can be read from the closure.

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +      //      actorsToResolve.foreach(actorPath => resolveActor(actorPath))
Why is it commented?

2017-05-02 17:14 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/roads/Road.scala
> +    if (1 == 1) {
Wtf? Condition always true.

2017-05-05 20:09 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +    def resolveActorWithRetries(actorPath: ActorPath, retries: Int)(implicit ec: ExecutionContext): Future[ActorRef] = {
Removed retry method. I don't know if futures are reusable, but it wasn't working. Found it on some scala forums.

2017-05-05 20:30 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/actors/AreaActor.scala
> +      //      actorsToResolve.foreach(actorPath => resolveActor(actorPath))
Removed. I was first trying to resolve all actors at once but it caused dead locks when there were thousands of futures for opposite resolveOne requests.

2017-05-05 20:31 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/roads/Road.scala
> +    if (1 == 1) {
no idea, only reformatted the file :) I'll remove it

2017-05-05 20:33 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/roads/Road.scala
> +    if (1 == 1) {
maybe there should be some variable used? (looking at the comment above)

2017-05-05 20:40 UTC, mjanczykowski commented on common/src/main/scala/miss/trafficsimulation/roads/Road.scala
> +    if (1 == 1) {
finally, I'll leave it :)

2017-05-06 15:02 UTC, salceson commented on common/src/main/scala/miss/trafficsimulation/roads/Road.scala
> +    if (1 == 1) {
Yeah, I understand that it's reformated only. But this is **very** suspicious. I'll look at this today - a bit later.

2017-05-08 19:34 UTC, closed without merging