Added initial association timeout
salceson/miss pull request #45
Opened 2017-06-27 21:19 UTC by mjanczykowski

2017-06-27 21:49 UTC, salceson requested changes

2017-06-27 21:49 UTC, salceson commented on common/src/main/resources/supervisor.conf
> +supervisor.waiting-for-workers-timeout-seconds = 60
We have some inconsistent ways of naming config values. Above we see `names-like-that`, `names_like_that`, below we see `names.like.that`. We need to decide one format.

2017-06-27 21:49 UTC, salceson commented on common/src/main/scala/miss/worker/WorkerActor.scala
> +class WorkerActor(supervisorPath: String, retryIntervalSeconds: Long, supervisorAssociationTimeoutSeconds: Long) extends FSM[State, Data] {
Long line (140 characters).

2017-06-27 21:49 UTC, salceson commented on common/src/main/scala/miss/worker/WorkerActor.scala
> +  private val ASSOCIATION_TIMER = "association-timer"
As far as I know, constants in Scala are named like this: `AssociationTimer`. This, of course is a convention. Are we using constants named like `ASSOCIATION_TIMER` everywhere?

2017-06-27 21:49 UTC, salceson commented on common/src/main/scala/miss/worker/WorkerActor.scala
> +  def props(supervisorPath: String, retryIntervalSeconds: Long,supervisorAssociationTimeoutSeconds: Long): Props = Props(classOf[WorkerActor], supervisorPath, retryIntervalSeconds, supervisorAssociat
Very long line, unformatted.

2017-06-28 18:12 UTC, mjanczykowski commented on common/src/main/resources/supervisor.conf
> +supervisor.waiting-for-workers-timeout-seconds = 60
I'll use underscore here, as I don't want to edit scripts.

2017-06-28 18:13 UTC, mjanczykowski commented on common/src/main/scala/miss/worker/WorkerActor.scala
> +  private val ASSOCIATION_TIMER = "association-timer"
fixed here + in Supervisor

2017-06-28 18:14 UTC, mjanczykowski commented on common/src/main/scala/miss/worker/WorkerActor.scala
> +  def props(supervisorPath: String, retryIntervalSeconds: Long,supervisorAssociationTimeoutSeconds: Long): Props = Props(classOf[WorkerActor], supervisorPath, retryIntervalSeconds, supervisorAssociat
fixed

2017-06-28 18:30 UTC, salceson approved these changes

2017-07-04 21:13 UTC, merged